server:
  port: 9090

spring:
  application:
    name: LibraryTgBot
  config:
    import: "optional:file:/configs/application-prod.yml"

  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:data/library_tg_bot_data.db
    username: ""
    password: ""
    hikari:
      schema: library_bot
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master-local.xml

scheduler:
  cron: "0 */10 * * * *"
  refresh-cron: "0 0 0 */2 * *"
#  cron: "*/15 * * * * *"

telegrambot:
  bot:
    username: LibraryTgBot
    token: "6435196077:AAH9ky7D0A6zgCD4qedCddaHFH_uZ9TEaLY" #dev
    support_chat_id: "-4918264185" #dev

