server:
  port: 9090

spring:
  application:
    name: HeadHunterMonitorBot
  config:
    import: "optional:file:/configs/application-prod.yml"

  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:data/hh_monitor_data.db
    username: ""
    password: ""
    hikari:
      schema: feature_toggle
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master-local.xml

scheduler:
  cron: "0 */10 * * * *"
  refresh-cron: "0 0 0 */2 * *"
#  cron: "*/15 * * * * *"

telegrambot:
  bot:
    username: HeadHunterMonitorBot
    token: "8325944541:AAE0MZjGBVlpYo-ATWwtzO6zVYYl8G6qksQ" #prod
#    token: "6435196077:AAH9ky7D0A6zgCD4qedCddaHFH_uZ9TEaLY" #dev
    support_chat_id: "-5039932829"  #prod
#    support_chat_id: "-4918264185" #dev

hh:
  redirect_url: https://hh.ru
  grant_type_access: authorization_code
  grant_type_refresh: refresh_token
